### ISSUE TITLE
GPU memory useage

### ISSUE THREAD

**Issue by WANG-Chaoyue** [rosinality/stylegan2-pytorch#10]
Thanks for your great work about reproducing the StyleGAN and its v2. 
I am running the styleganv2 code on my 2 GPU (2080ti) workstation. I found if I set the image resolution to 256x256, the maximum batch size I could achieve is 2. Yet, in the official implementation, they list that config-f on 256 resolution only takes 6.4GB GPU memory. I am wondering to know the difference between them, since it seems that I cannot implement 1024 resolution on my workstation (or even larger GPU station). BTW, have you tried how many GPUs could deal with 1024 resolution?
Thanks again!

**Comment by rosinality** [comment]
I think main reason for large memory consumption is due to generating samples during training. It makes 64 samples with 1 forward. (so, batch size 64.) If you skip sampling or split it with smaller batches then you can reduce memory consumption a lot.

**Comment by MengXinChengXuYuan** [comment]
I tried to skip producing sample images but the memory didn't show obivious changes
I also find that the memory used of different training size don't varies a lot like it should be
For me I tested using 128 takes 17800m, 256 takes 21000m, and 512 takes 24000m
Could be having too mush intermediate variables?

**Comment by rosinality** [comment]
In my cases train.py uses about 8.2 GB at 256px, batch size 8, path_batch_shrink 2. I think it is not very excessive memory consumption.

**Comment by WANG-Chaoyue** [comment]
Thanks for your answer! It indeed largely improved my batch size (although, as same as MengXinChengXuYuan, I also find that reduce batch size will not significantly change the GPU memory consumption). Meanwhile, using a single GPU, I find the code could train on 1024px with batch size = 2. It is impressive!

Yet, I raised a new problem. I found that after every 4 iterations, it takes a longer time to run the next iteration. It is acceptable on my 2080ti workstation. Yet, when I test it on the university's cluster (V100 GPUs), it takes much more time (around a few minutes per 4 iterations, much slower than my local workstation). Till now, I still cannot find the causes. I am wondering if you have any suggestions about this? Thanks a lot!

**Comment by rosinality** [comment]
For every 4 iterations path length regularization will be applied, so it will take longer time. But taking minutes is definitely strange. I think maybe it is related to the gather_grad step before current version. Could you try 82f7f55d600ccf6d8ef8e717b2981dd93be82d60?

**Comment by WANG-Chaoyue** [comment]
Thanks for such a quick reply. I actually test the latest code version, it still has this problem. Since the same code is definitely fine on my 2080ti workstation, I guess it should be PyTorch version (related dependencies) or hardware problem. On the 2080ti, I use the pytorch 1.3.1 with cuda 10.1. On the V100 cluster, I tried pytorch 1.3.0\1.4.0 wich cuda 10.0. 

Thanks for your answer, I will look into the path length regularization part and attempt to find the reason.

**Comment by WANG-Chaoyue** [comment]
I test the code again and found it should be the PyTorch version issues. I highly agree to keep the same version with authors, i.e., PyTorch 1.3.1 with Cuda 10.2 (for me, the Cuda 10.1 is also fine). 

Thanks again for your sharing and help. And I think this issue can be closed.
