### ISSUE TITLE
How to get image by special Z in pytorch realization?

### ISSUE THREAD

**Issue by Kupchanski** [rosinality/stylegan2-pytorch#103]
I try to make image by vector Z instead of random noize to reproduce special photo. 
Trying somethig like that:
```
z = np.load("z.npy")
latent_out = g_ema.style(torch.from_numpy(z))
latent_mean = latent_out.mean(0)
latent_in = latent_mean.detach().clone().unsqueeze(0).repeat(1, 1)
latent_in = latent_in.unsqueeze(1).repeat(1, g_ema.n_latent, 1)
```

But in the end after 
`img_gen, _ = g_ema([latent_in ], input_is_latent=True)`

I get different photo.
What I`m doing wrong?

```
If I take w_arg= Gs_network.get_var('dlatent_avg') from tf realization and then make
latent_vector = w_avg + (latent_in.detach().numpy() - w_avg) * 0.5
img_gen, _ = g_ema([latent_vector ], input_is_latent=True)

```
It gives me right photo. How get w_arg from torch realization?

**Comment by rosinality** [comment]
Converted checkpoints have 'latent_avg' items which corresponds to dlatent_avg.

**Comment by Kupchanski** [comment]
I see. It works, thank you so much!
