### ISSUE TITLE
Pre-trained model on MetFaces Dataset

### ISSUE THREAD

**Issue by hblflybird** [rosinality/stylegan2-pytorch#106]
Thanks for sharing your code, could you please share the pre-trained checkpoints trained on MetFaces dataset?

**Comment by justinpinkney** [comment]
You can get a different met faces model (trained with the original StyleGAN, but you should be able to convert it) here: https://github.com/justinpinkney/awesome-pretrained-stylegan2/#painting-faces

**Comment by rosinality** [comment]
You can use this checkpoints: https://drive.google.com/file/d/1g6URSv_0K3G0hy6s7ZLW5Sb1Bpaqd6CE/view?usp=sharing

But it is the results from my intermediate experiments with non leaking augmentations, and without FFHQ pretraining. So the result will be not very optimal. (For examples, I found "leaking" of augmentations behavior.)

**Comment by hblflybird** [comment]
Thanks for the replies!
