### ISSUE TITLE
Conversion of the weights from PyTorch to TensorFlow

### ISSUE THREAD

**Issue by woctezuma** [rosinality/stylegan2-pytorch#115]
Hello,

It is really handy to be able to import my TensorFlow model (trained with Nvidia's [original implementation](https://github.com/NVlabs/stylegan2) of StyleGAN2) to PyTorch, so that I am able to use your code for closed-form factorization (which is not yet made available in Genforce's [official repository](https://github.com/genforce/sefa)).

I see that you have implemented [training with limited data](https://arxiv.org/abs/2006.06676), which is not yet made available by Nvidia. I would be eager to try it, but I wonder whether I will be able to convert the PyTorch model to TensorFlow if I ever need to.

I find your code to convert from TensorFlow to PyTorch a bit intimidating. How easy would it be to convert the weights from PyTorch to TensorFlow, if I ever needed to? Would you know whethere there is any code already available for this purpose?

Thank you for your work and for your attention!

**Comment by rosinality** [comment]
I don't know the exact concern you have, anyway I have checked converted checkpoints produces almost same outputs, both generator and discriminator.

**Comment by woctezuma** [comment]
I trust your converter. I have seen the images produced by it, and it is true that the difference is zero.

My concern was more about portability of the model. It is only a thought: imagine there is some cool code in Tensorflow, and I want to export a model trained with PyTorch. Would I be able to?

**Comment by rosinality** [comment]
Ah, I got what you mean. I haven't trie,d but it coould be complicated or maybe hard to do as tensorflow checkpoint is somewhat less intuitive than pytorch. But if you find way to how to save tensors from pytorch to tensorflow checkpoints, rest would be not very hard.

**Comment by betterze** [comment]
@woctezuma @rosinality Did anyone solve this problem? I am using [StyleSpace](https://github.com/betterze/StyleSpace) and [StyleCLIP global](https://github.com/orpatashnik/StyleCLIP#editing-via-global-direction), which ultize stylegan2 tf to do manipulation in S space. Unfortunately, they only support tf version. 

I want to manipulate a model that pretrained by stylegan pytorch, so I need to convert the weights from pytorch to tf. Is there a way to do this?

Thank you for your help.
