### ISSUE TITLE
Could I resume training for a model trained elsewhere?

### ISSUE THREAD

**Issue by woctezuma** [rosinality/stylegan2-pytorch#116]
As mentioned in #115, I have trained a model with Nvidia's implementation, then converted it to PyTorch with your tool.

I am interested in your implementation of [training with limited data](https://arxiv.org/abs/2006.06676).

I am considering:
-   **resuming** training with your tool,
-   starting with my pre-trained model,
-   **with** the flag to augment data.

That would allow me not to waste what I already have, compared to training from scratch.

I think it should work, as the augmentation probability is increased over time anyway.

Would that make sense? Or would it be a bad idea? Or should I start from scratch because of the following?

![text](https://i.imgur.com/jQymSCd.png)
![text](https://i.imgur.com/XWOPL82.png)
![augmentation probability](https://i.imgur.com/85joc2h.png)

**Comment by rosinality** [comment]
I haven't tried, but I guess it would work. Also I think the cited part from the paper does not suggest against to it, as it is the case for scratch training. But you may need to adjust adaptive augmentation hyperparameters like ada_length so that augmentation probabilities increased quickly enough.

**Comment by woctezuma** [comment]
Thank you. That is right, I would need to ensure `p` increases quickly enough.

For now, I will set this project aside, because I encounter a small issue.
```bash
!python train.py \
 --ckpt /content/stylegan2-pytorch/network-snapshot-005000.pt \
 --channel_multiplier 1 \
 --augment \
 /content/stylegan2-pytorch/out_data/
```

```


load model: /content/stylegan2-pytorch/network-snapshot-005000.pt
Traceback (most recent call last):
  File "train.py", line 490, in <module>
    generator.load_state_dict(ckpt["g"])
KeyError: 'g'
```
