### ISSUE TITLE
I want to ask about the structure of the dataset

### ISSUE THREAD

**Issue by LIMr1209** [rosinality/stylegan2-pytorch#125]
hi
I want to ask about the structure of the dataset

**Comment by rosinality** [comment]
You need to use torchvision.datasets.ImageFolder compatible directory structure, that is, dataset directory should have subdirectory which is corresponds to class. (Though class information is not used in this implementation.)

**Comment by LIMr1209** [comment]
I see. Thank you

**Comment by LIMr1209** [comment]
如何使用多个GPU @rosinality
