### ISSUE TITLE
An error occurred while running convert_weight.py

### ISSUE THREAD

**Issue by oReano** [rosinality/stylegan2-pytorch#14]
![error](https://user-images.githubusercontent.com/30290565/71798435-01fb7480-308d-11ea-9f3e-8f3c34cb59ca.JPG)
Could you please help me to solve this problem?

**Comment by sebastianberns** [comment]
Hi! I have the same problem. Were you able to solve this?

**Comment by sebastianberns** [comment]
Solved it—
Relevant explanation here: https://stackoverflow.com/a/59205712
