### ISSUE TITLE
version of tensorflow and pytorch

### ISSUE THREAD

**Issue by banianzr** [rosinality/stylegan2-pytorch#146]
Hi, I tried to convert weights from the official checkpoints but failed. It's because your code is based on  PyTorch 1.3.1 and CUDA 10.1/10.2, while the official code is based Tensorflow 1.14 and CUDA 10.0. They're conflict and ```convert_weight.py``` requires ```import tensorflow as tf ```. Could you share your environment configuration for the conversion? Thanks in advance!

**Comment by rosinality** [comment]
I have used cuda 10.2 and tensorflow 1.15.

**Comment by banianzr** [comment]
I've tested during the past 2 days, and it seemed be solved:

First I created environment according to [NVlabs/stylegan2](https://github.com/NVlabs/stylegan2)'s requirement, mainly including ```tensorflow=1.15.0``` and ```cudatoolkit=10.0.130``` (see [nvidia-env.txt](https://github.com/rosinality/stylegan2-pytorch/files/5507753/nvidia-env.txt)) Then I continued to update the environment with 
```conda install pytorch==1.4.0 torchvision==0.5.0 -c pytorch```.

I tried this virtual environment on two machine, one Unbuntu 16.04 with two Nvidia 1080 (driver version: 430.40), the other Ubuntu 18.04 with two Nvidia 1080 Ti (driver version: 440.33.01). The former failed to allocate enough space and the latter successed. Also, during the conversion, there might be some problems, see [tensorflow error This file requires compiler and library support for the ISO C++ 2011 standard](https://stackoverflow.com/questions/59342888/tensorflow-error-this-file-requires-compiler-and-library-support-for-the-iso-c)
