### ISSUE TITLE
Question about batch size.

### ISSUE THREAD

**Issue by efirdc** [rosinality/stylegan2-pytorch#152]
Hello,

In the StyleGan2 paper they mention that they use a minibatch size of 32, and they train their models using 8 Tesla V100 GPUs. I am just not sure if this batch size is per-GPU or across all GPUs? I have tested this implementation on a single 32GB V100 GPU, and the largest batch size I could accomplish was 8. 12 worked for a bit but eventually runs out of memory.

If they were using 16GB V100 gpus then this is consistent since they would have a per-GPU batch size of 4, making the total size 4*8=32. However if it is 32 per-GPU then that means that this implementation is using a lot more memory than the official tensorflow implementation. I think the only way that could be possible is if the mixed precision that they use saves a lot of memory. Any ideas about what might be the case?

Thanks.

**Comment by rosinality** [comment]
Batch size in the official implementation corresponds to the total batch sizes across the gpus. So they have used batch size 4 per gpu.

**Comment by efirdc** [comment]
Thanks for the information. I suppose dividing up a batch of 32 into 8 GPUs leads to very fast training times. Maybe they could have done 8 per GPU but chose not to.
