### ISSUE TITLE
About the memory usage of GPU

### ISSUE THREAD

**Issue by tangjilin** [rosinality/stylegan2-pytorch#154]
Hi, thanks for your great work!
 I achieve my model based on your stylegan2 network.  When I train my model with batchsize=2 on a single GPU(11GB) without nn.parallel.DistributedDataParallel(), the memory usage of GPU is about 7.3 GB.  However, when I train my model with batchsize=2 per GPU on two GPUs(totally batchszie=4) with nn.parallel.DistributedDataParallel(), the memory usage of per GPU is about 8.4 GB.
Is it normal? What can I do to reduce the memory usage of GPU with nn.parallel.DistributedDataParallel()?
Thanks very much!

**Comment by rosinality** [comment]
While I cannot point out the reason of memory consumption, but increased memory consumption of about 1 GB will not mean DistributedDataParallel uses all of it, due to the nature of pytorch gpu memory allocator. (It pre-allocates gpu memory larger than actual memory consumptions.)
