### ISSUE TITLE
the issue of using generate.py to generate image

### ISSUE THREAD

**Issue by nhk19980516** [rosinality/stylegan2-pytorch#157]
I meet a problem my model can generate good image when training but my model generated a brown image when I used pretrained model by generate.py. I will appreciate if somebody can tell me how to solve the problem.
![111](https://user-images.githubusercontent.com/52226113/100575401-f6edaa80-3316-11eb-9c9a-ac4670801bdf.png)
![222](https://user-images.githubusercontent.com/52226113/100575420-ff45e580-3316-11eb-8e15-9d2a7817ebe0.png)

**Comment by crycrywolf** [comment]
excuse me，how did you solved this problems?
