### ISSUE TITLE
Question about loading from the checkpoint

### ISSUE THREAD

**Issue by tangjilin** [rosinality/stylegan2-pytorch#158]
Hi.
In your code, it seems you load the model into GPU, while the state_dict is loaded into CPU? For example,

device = 'cuda'
generator = Generator(
        args.size, args.latent, args.n_mlp, channel_multiplier=args.channel_multiplier
    ).to(device)

 if args.ckpt is not None:
        print("load model:", args.ckpt)
        ckpt = torch.load(args.ckpt, map_location=lambda storage, loc: storage)
        generator.load_state_dict(ckpt["g"])

generator (in GPU) load the state_dict from ckpt["g"] (in CPU). Is it ok? Thanks!

**Comment by rosinality** [comment]
Yes, it is not problematic.

**Comment by tangjilin** [comment]
Got it. Thanks.
