### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by Yan98** [rosinality/stylegan2-pytorch#161]
Hi,

Could I know when to stop training and how long it took for training in your case, please? Because I reimplement the dataset for my case, I'm not sure if the training slows.

Currently, I use 4 V100GPU with batch size 64 (distributed training) for 128x128 resolution, the estimated training time for 200000 iterations is 10 days. Is it a normal training time, please?

Thanks for your help.

**Comment by Yan98** [comment]
Found the answers... Thanks.

**Comment by calvinpelletier** [comment]
What was the answer?
