### ISSUE TITLE
Question about "Equal" linear

### ISSUE THREAD

**Issue by seungjunlee96** [rosinality/stylegan2-pytorch#162]
Hi, 

First, I want to say thank you for your great work. 

I have a question about the difference between the "equal" linear and default linear layer.

Specifically, I tried to implement an encoder network using your implementation of generator and discriminator but there was a significant drop in performance when I used "equal" linear instead of just linear layer. Just using the default linear layer showed better results than the "equal" linear for the final linear layers (I used the same convolutional layers for both approaches).

But I can't find the exact reason equal linear was worse and the meaning of "equal".

Thanks.

![image](https://user-images.githubusercontent.com/52485736/101868692-3e025800-3bc1-11eb-9747-9dbd4e4d9548.png)

```python
class EqualLinear(nn.Module):
    def __init__(
        self, in_dim, out_dim, bias=True, bias_init=0, lr_mul=1, activation=None
    ):
        super().__init__()

        self.weight = nn.Parameter(torch.randn(out_dim, in_dim).div_(lr_mul))

        if bias:
            self.bias = nn.Parameter(torch.zeros(out_dim).fill_(bias_init))
        else:
            self.bias = None

        self.activation = activation

        self.scale = (1 / math.sqrt(in_dim)) * lr_mul
        self.lr_mul = lr_mul

    def forward(self, input):
        if self.activation:
            out = F.linear(input, self.weight * self.scale)
            out = fused_leaky_relu(out, self.bias * self.lr_mul)

        else:
            out = F.linear(
                input, self.weight * self.scale, bias=self.bias * self.lr_mul
            )

        return out

```

**Comment by rosinality** [comment]
You will need to use different learning rates for equal or norm linear layers. Generally you need to use larger learning rates for equal linear.

**Comment by seungjunlee96** [comment]
Thanks for your reply!
