### ISSUE TITLE
Errors Running on Colab

### ISSUE THREAD

**Issue by cyrilzakka** [rosinality/stylegan2-pytorch#17]
When running the command `!python -m torch.distributed.launch --nproc_per_node=1 --master_port=1234 train.py --batch 1 /content/data/preprocessed` on Google Colab, it first complains that 'Ninja is required to load C++ extensions' which can be fixed by running `pip install ninja`.

Unfortunately running the command again after restarting runtime returns the following error which I can't seem to get around: 

 ```
 0% 0/800000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 253, in <module>
    main()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/launch.py", line 249, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'train.py', '--local_rank=0', '--batch', '1', '/content/data/preprocessed']' died with <Signals.SIGFPE: 8>.
```

Any idea on how to get this to work?

**Comment by rosinality** [comment]
I thinks it is related to pytorch, as you don't need to install ninja separately.

**Comment by cyrilzakka** [comment]
PyTorch and CUDA versions match the ones mentioned in the README. I think the issue was with the batch number being too small - changing it seemed to get things running

**Comment by Selimonder** [comment]
A small helper script for converting weights on google colab,

https://colab.research.google.com/drive/1OtRXSTK720kBVfkP_YboTJvxC5-7iAak

**Comment by stone100010** [comment]
> A small helper script for converting weights on google colab,
> 
> https://colab.research.google.com/drive/1OtRXSTK720kBVfkP_YboTJvxC5-7iAak

Can you send me this file? 493173142@qq.com,thanks!

**Comment by stone100010** [comment]
> A small helper script for converting weights on google colab,
> 
> https://colab.research.google.com/drive/1OtRXSTK720kBVfkP_YboTJvxC5-7iAak

Nice!
