### ISSUE TITLE
Takes too long to train - Gets stuck every 4 iterations

### ISSUE THREAD

**Issue by yoniker** [rosinality/stylegan2-pytorch#175]
So I have a machine with a 2080Ti, I've tried to run the code as instructed at Readme.

It takes more than 4 seconds per iteration on average (image size is the default 256,I reduced batch size to 4).
After each 4 iterations (each running by itself way faster than 1 sec) it's getting "stuck" s eg 1,2,3,4 then something holds it  for a long time,then 5,6,7,8 then stuck again etc.
What do you think it could be?

I've created the dataset from the celeba raw images as instructed (with just one size of 256), and then ran
python -m torch.distributed.launch  train.py --batch 4 <Dataset dir>

Thanks in advance man :)

**Comment by rosinality** [comment]
It is due to path length regularization. You can turn off it if you need. (Generally it will not affect much to the sample quality.) https://github.com/rosinality/stylegan2-pytorch/blob/master/train.py#L231

**Comment by yoniker** [comment]
Yep, that was the reason! Thx, much appreciated!
By the way, what's the reason i don't see exponential moving average?
Did I miss it or do you think it's not that important in order to get good sample quality?

**Comment by rosinality** [comment]
EMA is used in here. https://github.com/rosinality/stylegan2-pytorch/blob/master/train.py#L259.

**Comment by genghisun** [comment]
I found that with [A100 GPUs, PyTorch 1.7.1, CUDA 11], these two lines (https://github.com/rosinality/stylegan2-pytorch/blob/master/train.py#L248-L250) will cause a stuck of about 292 seconds. But with [V100 GPUs, PyTorch 1.4.0, CUDA 10.2], g_path_regularize is fast, which only takes about 0.8s.
Does anyone know what's going on?

**Comment by rosinality** [comment]
@genghisun Maybe there suboptimal operations for A100/CUDA 11 in the double backpropagation. It is hard to know why without profiling.

**Comment by yoniker** [comment]
To clarify-  but it's normal for g_reg_every to significantly slow down the training process even after optimization?

**Comment by rosinality** [comment]
Yes, low vale of g_reg_every means more frequent apply of path length regularization, which is quite heavy.

**Comment by onion-liu** [comment]
> I found that with [A100 GPUs, PyTorch 1.7.1, CUDA 11], these two lines (https://github.com/rosinality/stylegan2-pytorch/blob/master/train.py#L248-L250) will cause a stuck of about 292 seconds. But with [V100 GPUs, PyTorch 1.4.0, CUDA 10.2], g_path_regularize is fast, which only takes about 0.8s.
> Does anyone know what's going on?

I meet the same problem, have you solved it?

**Comment by yx-chan131** [comment]
> @genghisun Maybe there suboptimal operations for A100/CUDA 11 in the double backpropagation. It is hard to know why without profiling.

Hi, I also faced the same problem. I still can't figure out the reason behind this because the training speed of discriminator regularization is looking okay... According to the code https://github.com/rosinality/stylegan2-pytorch/blob/master/train.py#L203-L218, I think the discriminator also having the double backpropagation.
