### ISSUE TITLE
generated image from converted checkpoint different

### ISSUE THREAD

**Issue by alfinnurhalim** [rosinality/stylegan2-pytorch#178]
Hi, thank you for your amazing implementation

I currently got an issue, do you know why the generated image from the converted weight is way different than the original .pkl does?

here is the output from the original .pkl 
![image](https://user-images.githubusercontent.com/44990448/104905635-377fb100-59b5-11eb-82fa-7453dc0dd1d5.png)

here is the output from the converted weight
![image](https://user-images.githubusercontent.com/44990448/104905711-4fefcb80-59b5-11eb-9afc-81463320ba13.png)

do you have any idea?

**Comment by rosinality** [comment]
I cannot guess the exact reason. But it seems like that it is related rgb colorization. You need to check `to_rgbs` or image normalizations.
