### ISSUE TITLE
How to apply the xxx.pt file completed in projector.py to apply_factor.py?

### ISSUE THREAD

**Issue by chengkeng** [rosinality/stylegan2-pytorch#185]
Hi！
We added the parameter of channel_multiplier and got a xxx.pt file in projector.py. Can this file be used in apply_factor.py? I tried to use it as a factor file, but it appeared:
File "apply_factor.py" in <module>, line 57
       eigvec = torch.load(args.factor)["eigvec"]. to (args.device)
KeyError: "eigvec"
Is this the wrong way to use it?
thank you very much!

**Comment by rosinality** [comment]
You can replace latent in https://github.com/rosinality/stylegan2-pytorch/blob/master/apply_factor.py#L65 to the latent you got from projector.py. You need to do closed form factorization using https://github.com/rosinality/stylegan2-pytorch/blob/master/closed_form_factorization.py and get the factor file before to use apply_factor.py.

**Comment by chengkeng** [comment]
> You can replace latent in https://github.com/rosinality/stylegan2-pytorch/blob/master/apply_factor.py#L65 to the latent you got from projector.py. You need to do closed form factorization using https://github.com/rosinality/stylegan2-pytorch/blob/master/closed_form_factorization.py and get the factor file before to use apply_factor.py.

Yes, you have told us in the documentation that we need to get factor.pt first, and random samples can be edited at will, very successful and perfect. But where should the xxx.pt obtained from projector.py be arranged in apply_factor.py?

Should I add or modify the code in apply_factor.py?

L31 parser.add_argument("--pjpt", type=str, default=None, help="projector pt")
L58 pjpt = torch.load(args.pjpt)
L60 g.load_state_dict(pjpt["g_ema"], strict=False)？
L65 latent = g.get_latent(latent)？

**Comment by rosinality** [comment]
You can load xxx.pt and use `'latent'` in it instead of https://github.com/rosinality/stylegan2-pytorch/blob/master/apply_factor.py#L65.

**Comment by chengkeng** [comment]
> You can load xxx.pt and use `'latent'` in it instead of https://github.com/rosinality/stylegan2-pytorch/blob/master/apply_factor.py#L65.


But how can the latent load it without modifying this line of code?
Although ckpt.pt, factor.pt, and xxx.pt are all pt files, the usage is completely different. 
It is difficult for me to find the correct code format to replace latent. 
Could you give me more tips?
 Thank you！

**Comment by rosinality** [comment]
You can just use it like `latent = torch.load('xxx.pt')[INPUT_FILE_NAME]['latent']`
