### ISSUE TITLE
About opening multiple projector latents for visual editing.

### ISSUE THREAD

**Issue by chengkeng** [rosinality/stylegan2-pytorch#186]
Hi！
This is the valuable code obtained last time！
latent = torch.load("seed0390.pt")[" seed0390.png"] ['latent']
Thanks again!

This time I tried to replace it with our projector latent in ganspace.
But I found that the way it imports multiple latents seems to be different.

It uses a minimum of 1 and a maximum of 9 consecutive seeds arranged in the window.

The code is：
------------------------------------------------   ---------------------------------------
#- Use consecutive seeds along batch dimension (for easier reproducibility)
trunc = ui_state.truncation.get()
latents = [model.sample_latent(1, seed=state.seed + i, truncation=trunc) for i in range(B)]

state.z = torch.cat(latents).clone().detach() # make leaf node
---------------------------------------------    ----------------------------------------

My modification is:
----------------------------------------------    --------------------------------------------
latents = [model.sample_latent(1, seed=state.seed + i, truncation=trunc) for i in range(B)]
UseProjector=1
if UseProjector is not 0:
    latents = [torch.load("seed0390.pt")["seed0390.png"]['latent'] for i in range(B)]

state.z = torch.cat(latents).clone().detach() # make leaf node
------------------------------------------    ----------------------------------------------
The last error displayed is：

  File "C:\MyWork\My_GAN_Work\GanSpace\models\stylegan2\stylegan2-pytorch\model.py", line 158, in forward
    input, self.weight * self.scale, bias=self.bias * self.lr_mul
  File "C:\Users\Creator\miniconda3\envs\NewGanSpace\lib\site-packages\torch\nn\functional.py", line 1674, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0
--------------------------------------------    ----------------------------------------------
I searched on Google and there is no suitable solution for this.
I print both latents：

When:
latents = [model.sample_latent(1, seed=state.seed + i, truncation=trunc) for i in range(B)]
------------------------------------------    ---------------------------------------------------
[tensor([[ 0.4823,  2.6367,  0.7104...............................................................

...........................-0.0974,  2.0732,  0.1296, -0.3443,  0.3176, -0.3265]],
device='cuda:0', grad_fn=<FusedLeakyReLUFunctionBackward>)]
----------------------------------------   ---------------------------------------------------------
When：
latents = [torch.load("seed0390.pt")["seed0390.png"]['latent'] for i in range(B)]
------------------------------------   -----------------------------------------------------------
[tensor([ 0.5785,  3.9734, -0.7133..............................................................
.................................. 0.5757, -3.3597,  1.6575,  1.3914],
device='cuda:0', requires_grad=True)]
------------------------------------------    ------------------------------------------------
It seems that the output format of the two latents is still inconsistent.
I tried adding:
truncation=args.truncation,
truncation_latent=trunc,
input_is_latent=True,
But the results are unable to make the format consistent.
Especially the end part, it's：
grad_fn=<FusedLeakyReLUFunctionBackward>
Ours is:
requires_grad=True
Should they be handled in other ways so that they can be used consistently? 
Thank you!

**Comment by rosinality** [comment]
I think you need to use `torch.stack` instead of `torch.cat`.
