### ISSUE TITLE
Add a requirements.txt 

### ISSUE THREAD

**Issue by adeptflax** [rosinality/stylegan2-pytorch#190]
I get this error when running convert_weight.py:
```
AttributeError: module 'torch.jit' has no attribute '_script_if_tracing'
```
what module versions am I suppose to use?

**Comment by adeptflax** [comment]
I'm trying to get this working on cpu. I removed the fused and  upfirdn2d load functions in fused.py and upfirdn2d.py. They didn't seem to do anything useful when cpu mode is set in the source code. I don't have a cuba gpu on my laptop.

**Comment by rosinality** [comment]
Could give me a full error message? Anyway, please try to use pytorch >= 1.7.

**Comment by adeptflax** [comment]
I get the same error as issue #164. Which was caused by me installing this https://github.com/podgorskiy/dnnlib . It seems I need a cuba gpu to run to do the convention.

**Comment by adeptflax** [comment]
ok it seems it was a similar not the same error.

**Comment by nscalo** [comment]
Did anyone get a workaround for this problem? I'm also trying to run the StyleGAN2 model in Pytorch in CPU because I do not have a CUDA GPU. 

I replaced FusedLeakyReLU to LeakyReLU
But I'm figuring out what to do with UpFirdn2d Module?

Anyone has got conversion code for UpFirdn2d?
