### ISSUE TITLE
Pretrained Discriminator

### ISSUE THREAD

**Issue by mbbrodie** [rosinality/stylegan2-pytorch#20]
Thanks for your repo!
Can you add functions to convert the pretrained TF Discriminators?

E.g.
In [convert_weight.py](https://github.com/rosinality/stylegan2-pytorch/blob/master/convert_weight.py), you have
`_, _, g_ema = pickle.load(f)`

Can you update the conversion scripts to allow:
`_, D, g_ema = pickle.load(f)`

**Comment by rosinality** [comment]
Added discriminator porting options in fd039ed.

**Comment by mbbrodie** [comment]
It works -- thank you!

You may want to update your README from
`python convert_weight.py --repo ~/stylegan2 stylegan2-ffhq-config-f.pkl`
to
`python convert_weight.py --repo ~/stylegan2 --gen [--disc] stylegan2-ffhq-config-f.pkl`
