### ISSUE TITLE
How to evaluate the model after training.

### ISSUE THREAD

**Issue by shoutOutYangJie** [rosinality/stylegan2-pytorch#208]
I cost two weeks to train your repo, Now I want to evaluate, but I can't find the test code.

**Comment by shoutOutYangJie** [comment]
And Why do you use EMA to update the model rather than directly optimize the model?

**Comment by rosinality** [comment]
You can use fid.py.

**Comment by CrossLee1** [comment]
@rosinality 
I trained the model with 256px on FFHQ for 27k iterations, and used 
`python fid.py --inception inception_ffhq.pkl checkpoint/270000.pt` 
to evaluation the model, got `fid: 5.205281282400563`.

I have two questions:
1/ can I directly use your provided `inception_ffhq.pkl` for evaluation (256pix)
2/ I got fid 5.2 after 27k iterations, is it normal?

Thanks~

**Comment by rosinality** [comment]
@CrossLee1 I think it is reasonable score for this implementation.

**Comment by youdutaidi** [comment]
> 

Do you know where could I get the author's provided inception_ffhq.pkl?
Is this url?
'https://github.com/mseitzer/pytorch-fid/releases/download/fid_weights/pt_inception-2015-12-05-6726825d.pth'
