### ISSUE TITLE
Error reading images when running train.py on custom dataset 

### ISSUE THREAD

**Issue by cyrilzakka** [rosinality/stylegan2-pytorch#22]
When running `!python train.py --batch 32 /content/data/preprocessed/` on a custom dataset that was run through` !python prepare_data.py --out /content/data/preprocessed/ --n_worker 2 --size 32 /content/` first, an error is returned regarding `Image` being unable to read the image from buffer:

```
0% 0/800000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 434, in <module>
    train(args, loader, generator, discriminator, g_optim, d_optim, g_ema, device)
  File "train.py", line 179, in train
    real_img = next(loader)
  File "train.py", line 58, in sample_data
    for batch in loader:
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/stylegan2-pytorch/dataset.py", line 37, in __getitem__
    img = Image.open(buffer)
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7f2714825af0>
```

I thought this would be a buffer issue but still unable to isolate the problem. I'll report back as soon as I do

**Comment by cyrilzakka** [comment]
I've isolated the issue to the following line where `img_bytes` returns `None`
```
with env.begin(write=False) as txn:
  key = f'{256}-{str(0).zfill(5)}'.encode('utf-8')
  img_bytes = txn.get(key)
```

I'll report back with an actual solution

**Comment by cyrilzakka** [comment]
Figured it out. It seems `self.resolution = resolution` is not being assigned properly in `dataset.py` so in the [following line](https://github.com/rosinality/stylegan2-pytorch/blob/c05c15175aa2e8b7032e36d00a4b952da37a6b41/dataset.py#L33), `key` always starts at 256 regardless of the resolution picked by the user therefore raising the error.

**Comment by rosinality** [comment]
I will correct it. (I have put off supporting different image sizes...)

**Comment by cyrilzakka** [comment]
Oh my bad for rushing things! I was under the impression multiple image sizes were supported - just not progressive growing. Thank you for your work on this implementation though!

**Comment by cyrilzakka** [comment]
This issue was fixed and should thus be closed.
