### ISSUE TITLE
Questions about the version of gcc

### ISSUE THREAD

**Issue by JinshuChen** [rosinality/stylegan2-pytorch#220]
Hi. Thank you for your hard work and excellent code! When I use your 550000.pt and generate.py, I met the warning saying

“Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.”

Then the code exited with the Segmentation fault.
I guess the reason is about the CUDA op used in the project (fused_act, etc.) The version of my gcc is 4.8.5 which is default with my OS and I guess it may be too low for the code.
I wonder what's your version of gcc? Or do you know what exactly results in such warnings?

Thank you!

**Comment by rosinality** [comment]
I have used gcc 5.4.0 or 7.5.0. It seems like that to use custom extensions, you need to use gcc >= 4.9. https://pytorch.org/tutorials/advanced/cpp_extension.html

**Comment by JinshuChen** [comment]
> I have used gcc 5.4.0 or 7.5.0. It seems like that to use custom extensions, you need to use gcc >= 4.9. https://pytorch.org/tutorials/advanced/cpp_extension.html

Thank you for your information. The problems have been solved after I built a new gcc-7.5.0.
