### ISSUE TITLE
Noise in generating 256px images from pretrained model

### ISSUE THREAD

**Issue by pulkitgo** [rosinality/stylegan2-pytorch#234]
Hi! Just wanted to confirm, since noises are not stored in the pre-trained weights for 256px (550000.pt), and NoiseInjection.weight is initialised to zeros, that means during generation from pre-trained we do not incorporate any noise in the process? Thanks.

**Comment by rosinality** [comment]
Noise is not stored in checkpoints, but NoiseInjection.weight will be non-zero I think. So you can incorporate the noises.

**Comment by pulkitgo** [comment]
This is from `model.py`:
 
```python
class NoiseInjection(nn.Module):
    def __init__(self):
        super().__init__()

        self.weight = nn.Parameter(torch.zeros(1))

    def forward(self, image, noise=None):
        if noise is None:
            batch, _, height, width = image.shape
            noise = image.new_empty(batch, 1, height, width).normal_()

        return image + self.weight * noise
``` 
I believe during training the weight param will be trained, but during inference due to zero initialization noise would most probably have no effect. Please correct me if I am wrong, Thanks

**Comment by rosinality** [comment]
NoiseInjection.weight is saved in the checkpoints, so it will be loaded when state_dict is loaded.

**Comment by pulkitgo** [comment]
Thanks !
