### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by cs20162004** [rosinality/stylegan2-pytorch#236]
I am trying to train SWAGAN network for another task. For this I am using your generator and discriminator with small modification (the size of tensors and size of the network). However, when I run my code I get the following error. @rosinality  Do you have any idea on how to fix this?

![Screenshot from 2021-06-30 10-42-55](https://user-images.githubusercontent.com/46070112/123890520-4cb03100-d992-11eb-8490-0d59d68026c9.png)
Thank you!

**Comment by cs20162004** [comment]
For other people who are facing the same error: You need to use `broadcast_buffers=False` inside your `torch.nn.parallel.DistributedDataParallel()`

**Comment by HAN-oQo** [comment]
Hi, @cs20162004 
I have the same issue and your solution works for me . 
I just wonder whether the 'broadcast_buffers = False' option setting harms the performance  or not.
Can you share your result?

Thank you!
best regards,
Hankyu.
