### ISSUE TITLE
About the latent average code for your 256 stylegan2 generator

### ISSUE THREAD

**Issue by NNNNAI** [rosinality/stylegan2-pytorch#239]
Thanks for sharing your work!! I noticed that "latent_avg" is saved in the "stylegan2-ffhq-config-f.pt", while your self_training 256 stylegan2 did not got such a element. Is it possible to get such a element for the 256 stylegan2? Many thanks~. Have a nice day~.

**Comment by rosinality** [comment]
It is (running) average of latent codes, so I think you can replace it with plain average of latent vectors.

**Comment by NNNNAI** [comment]
Thanks for your respond! How could I get plain average of latent vectors for the 256 stylegan generator,thanks for your help~~~~~.Have a nice day.

**Comment by rosinality** [comment]
You can use `generator.mean_latent(n_sample_for_average)`

**Comment by NNNNAI** [comment]
It works! Thanks for your help~.
