### ISSUE TITLE
A bug when load upfirdn2d

### ISSUE THREAD

**Issue by JuncFang-git** [rosinality/stylegan2-pytorch#240]
This is a record about a bug.

When I want to train the second model use the command: CUDA_VISIBLE_DEVICES=1 python train.py xx xx xx. Despite a long wait, I didn't get any output. 

After I KeyboardInterrupt the program, I found it sleep at load upfifdn2d.
![image](https://user-images.githubusercontent.com/76929740/126275372-87fe0556-70d1-4197-ba24-b64cf0bd4e26.png)

**Comment by JuncFang-git** [comment]
I fix it by removed the cache folder 'upfirdn2d' at '~/.cache/torch_extensions'.
It may be a wrong cache file caused by some operation， so，rebuild the cache file is needed.

**Comment by whyydsforever** [comment]
how can I find this folder, where my .cache doesn't have the torch_extension folder
