### ISSUE TITLE
Could you please add the pretrained models for 512px and 1024px as well

### ISSUE THREAD

**Issue by vinayakarannil** [rosinality/stylegan2-pytorch#243]
Currently you have provided a pretrained model of 256px, would it be possible to upload the trained weights of 512px and 1024px as well?

**Comment by vinayakarannil** [comment]
Never mind...used the converted weights from the original repo. Thanks for the wonderful work !!

**Comment by JSHZT** [comment]
@vinayakarannil Could you please share your converted checkpoint? I've been having trouble with his conversion script
