### ISSUE TITLE
question about fid calculation for custom dataset

### ISSUE THREAD

**Issue by vinayakarannil** [rosinality/stylegan2-pytorch#244]
Thanks for the great work. I have trained the model with my custom dataset. Now i have to evaluate the fid. I can see from fid.py that it loads the precomputed mean/cov of real data, and then compare with the generated samples. So for a custom data how should i create the real image inception pickle file?

**Comment by vinayakarannil** [comment]
I did it using the calc_inception.py for real images. Hopefully this is the way to do it

**Comment by rosinality** [comment]
Yes, you can use calc_inception.py
