### ISSUE TITLE
floating point exception when batch size is 1

### ISSUE THREAD

**Issue by pc4653** [rosinality/stylegan2-pytorch#25]
When batch size is set to 1 and path_batch_shrink is unchanged, the program halts to floating point exception due to args.batch // args.path_batch_shrink == 0 in
 noise = mixing_noise(
                args.batch // args.path_batch_shrink, args.latent, args.mixing, device
            )
probably worth pointing out.

Also the implementation follows config-f in the paper i am assuming?

**Comment by rosinality** [comment]
Fixed at 0a35fdb. You can use config-f or config-e (by set --channel_multiplier 1 and -r1 100.)
