### ISSUE TITLE
Serious Performance Decay of `prepare_data.py` Over Time

### ISSUE THREAD

**Issue by DIMPLY** [rosinality/stylegan2-pytorch#263]
I'm processing a large amount of data using `prepare_data.py`. It seems using a multi-core machine didn't help with the performance.

When I ran 16 workers or 32 workers on a 32-core machine, it's running at 16-40 iter/s from the beginning.
When I ran 2 workers on the same 32-core machine, it reached 120-150 iter/s at the beginning.

What's more, however I set the number of workers and the number of cores on the machine, the performance always decays over time. It slows down to 10-20 iter/s after less than an hour.

Does anyone know what caused the performance issue here?

**Comment by DIMPLY** [comment]
I have 2 million images, and I believe each iter processes one image.
I only finished less than 100 thousand iters after 55 minutes.
It would be impossible to finish my task if I don't find a way to improve the performance.

**Comment by rosinality** [comment]
I think you can check cpu usage of the workers.

Sometimes if python binding uses multithreading then overall multiprocessing performances could be dropped. But I think it maybe not the case as prepare_data.py simply uses pillow. Or it could be IO problems.

I think it will be better to resize and convert image files manually.

**Comment by DIMPLY** [comment]
I found the processes in Google Cloud Console.


12828 | python3 prepare_data.py --out /home/yanyang/data/prepared_t_cell --size 256 --n_worker 4 /home/yanyang/data/raw | 0.32% | 841 MiB | 199 KiB/s | 0 byte/s |  
-- | -- | -- | -- | -- | -- | --
12831 | python3 prepare_data.py --out /home/yanyang/data/prepared_t_cell --size 256 --n_worker 4 /home/yanyang/data/raw | 0.32% | 841 MiB | 205 KiB/s | 0 byte/s |  
12830 | python3 prepare_data.py --out /home/yanyang/data/prepared_t_cell --size 256 --n_worker 4 /home/yanyang/data/raw | 0.32% | 841 MiB | 195 KiB/s | 0 byte/s |  
12829 | python3 prepare_data.py --out /home/yanyang/data/prepared_t_cell --size 256 --n_worker 4 /home/yanyang/data/raw | 0.32% | 841 MiB | 195 KiB/s | 0 byte/s |  
12779 | python3 prepare_data.py --out /home/yanyang/data/prepared_t_cell --size 256 --n_worker 4 /home/yanyang/data/raw | 0.16% | 37 GiB | 0 byte/s | 4 MiB/s

**Comment by DIMPLY** [comment]
Increased to 32 workers + changed output path from a mounted path to local path

16075 | python3 prepare_data.py --out /prepared_t_cell --size 256 --n_worker 32 /home/yanyang/data/raw | 1.81% | 840 MiB | 0 byte/s | 0 byte/s |  
-- | -- | -- | -- | -- | -- | --
16095 | python3 prepare_data.py --out /prepared_t_cell --size 256 --n_worker 32 /home/yanyang/data/raw | 1.81% | 840 MiB | 0 byte/s | 0 byte/s |  
16025 | python3 prepare_data.py --out /prepared_t_cell --size 256 --n_worker 32 /home/yanyang/data/raw | 1.19% | 16 GiB | 0 byte/s | 1 MiB/s

**Comment by DIMPLY** [comment]
I solved the problem by using an ssd boot disk, and copied all my data to the boot disk before running `prepare_data.py`.
