### ISSUE TITLE
Does anyone know how to convert .pt model to onnx?

### ISSUE THREAD

**Issue by zdj1414** [rosinality/stylegan2-pytorch#276]
I have converted the stylegan2 pkl model to pt model through convert_weight.py, but the pt model can't load on the android, so i want to convert the pt model to onnx.

I run the following code on colab:
```
!pip install torch==1.8.1 torchvision==0.9.1 torchaudio==0.8.1

from model import Generator
g_ema = Generator(1024, 512, 8, channel_multiplier=2).to('cuda')
g_ema.load_state_dict(ckpt["g_ema"])
g_ema.eval()
sample_z = torch.randn(1, 512, device='cuda')
torch.onnx.export(g_ema, [sample_z], "/content/ffhq-cartoon-blended-64.onnx", verbose=True, input_names=['styles'], output_names=['image'], opset_version=9)
```

output:
/content/stylegan2-pytorch/op/conv2d_gradfix.py:138: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out = F.conv2d(input=input, weight=weight, bias=bias, **common_kwargs)
/content/stylegan2-pytorch/op/conv2d_gradfix.py:146: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  **common_kwargs,

RuntimeError: 0 INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/ir/alias_analysis.cpp":532, please report a bug to PyTorch. We don't have an op for aten::normal but it isn't a special case.  Argument types: Tensor, float, float, None,

**Comment by rosinality** [comment]
It seems like that although tracing the mode is possible, but exporting it to onnx is not possible as there are missing operator supports in onnx.

**Comment by zdj1414** [comment]
thanks, I'll see if there's any other way

**Comment by Wheest** [comment]
Hi there, I was facing a similar issue with [stylegan2-ada-pytorch](https://github.com/NVlabs/stylegan2-ada-pytorch), and I managed to make a fork of that which allows you to export to ONNX.

You can [see the fork and instructions here](https://github.com/Wheest/stylegan2-ada-pytorch).  The model is ofc slightly different from StyleGAN2, but perhaps this methodology could be repeated for this repo.  Namely, the custom ops can be redefined using pure PyTorch.

**Comment by MarkZXZX** [comment]
> thanks, I'll see if there's any other way

Hi，Do u get any solution?
