### ISSUE TITLE
Weird incrementing of latents for W+ space with RGB layers?

### ISSUE THREAD

**Issue by dave-epstein** [rosinality/stylegan2-pytorch#278]
Hi,

Let's say the overall architecture of SGAN using terminology from this repo is as follows:
conv1 - to_rgb1 - self.convs[0] - self.convs[1] - self.to_rgbs[0] - ....

I noticed that when indexing into the tensor of latents (of dimension [batch size, number of latents, ...]), adjacent (rgb,conv) pairs use the same index. For example, to_rgb1 and self.convs[0] both get latent[:, 1]. When incrementing i in the for loop (https://github.com/rosinality/stylegan2-pytorch/blob/master/model.py#L549) it is apparent that adjacent calls to to_rgb at the end of an iteration and conv1 at the beginning of the next one use the same latent.

Is this by design? My intuition says that a more granular control over W+ space would give a separate latent to each and every time modulation happens.

Thanks for your great work on this codebase!

**Comment by rosinality** [comment]
Yes, it is the design from the official implementations. I don't know exact why the authors choosed that design, but as distinct latents only appears with style mixing augmentations, I think it is beneficial or reasonable to make latent codes for conv/to_rgbs to be same even when style mixing happens.

**Comment by dave-epstein** [comment]
I figured. Thanks!
