### ISSUE TITLE
About the resolution (FFHQ)

### ISSUE THREAD

**Issue by TiankaiHang** [rosinality/stylegan2-pytorch#279]
Hi,

Thanks for  your nice work!!

I have a question. Can the pretrained model for 1024x1024 FFHQ image generation be directly used for 256x256 ?

Best.

**Comment by rosinality** [comment]
No, although skip connection is used, color ranges and shapes will be different.

**Comment by TiankaiHang** [comment]
Got that. Thanks for your kind reply!

**Comment by freedom521jin** [comment]
> No, although skip connection is used, color ranges and shapes will be different.

Recently, I wanna use the pretrained model for 1024x1024 FFHQ image generation to train my own datasets , which is 512x512.
What should i do?

**Comment by rosinality** [comment]
@freedom521jin You can remove layers for 1024px in pretrained model, or you can try to add 1/2x and 2x resample layers in the generator and discriminator.
