### ISSUE TITLE
generate.py loading model problems, missing keys, discolored images

### ISSUE THREAD

**Issue by harryli0088** [rosinality/stylegan2-pytorch#283]
Hello! I trained StyleGAN2 on a dataset of gemstone images. Could you help me with some problems I have when I run `generate.py`?

Running `generate.py` normally gives me this error:

```
RuntimeError: Error(s) in loading state_dict for Generator:
	Missing key(s) in state_dict: "convs.12.conv.weight", "convs.12.conv.blur.kernel", "convs.12.conv.modulation.weight", 
"convs.12.conv.modulation.bias", "convs.12.noise.weight", "convs.12.activate.bias", "convs.13.conv.weight", 
"convs.13.conv.modulation.weight", "convs.13.conv.modulation.bias", "convs.13.noise.weight", "convs.13.activate.bias", 
"convs.14.conv.weight", "convs.14.conv.blur.kernel", "convs.14.conv.modulation.weight", "convs.14.conv.modulation.bias", 
"convs.14.noise.weight", "convs.14.activate.bias", "convs.15.conv.weight", "convs.15.conv.modulation.weight", 
"convs.15.conv.modulation.bias", "convs.15.noise.weight", "convs.15.activate.bias", "to_rgbs.6.bias", 
"to_rgbs.6.upsample.kernel", "to_rgbs.6.conv.weight", "to_rgbs.6.conv.modulation.weight", "to_rgbs.6.conv.modulation.bias", 
"to_rgbs.7.bias", "to_rgbs.7.upsample.kernel", "to_rgbs.7.conv.weight", "to_rgbs.7.conv.modulation.weight", 
"to_rgbs.7.conv.modulation.bias", "noises.noise_13", "noises.noise_14", "noises.noise_15", "noises.noise_16"
```

Running `generate.py` with `g_ema.load_state_dict(checkpoint["g_ema"], strict=False)` works, but the images seem weirdly discolored

Generated discolored images:
<p float="left">
<img src="https://user-images.githubusercontent.com/10376362/148974663-44ab498a-251a-4e44-8ff5-41207e94ce0c.png" width="200" />
<img src="https://user-images.githubusercontent.com/10376362/148974665-d07c6908-494c-45e2-b458-2079d97c0505.png" width="200" />
<img src="https://user-images.githubusercontent.com/10376362/148974668-b5cb6fce-6cf8-437c-863c-eb52fdb686a3.png" width="200" />
<img src="https://user-images.githubusercontent.com/10376362/148974670-e02dc7d9-2d8a-403f-9f6d-c1302b4df6e1.png" width="200" />
<img src="https://user-images.githubusercontent.com/10376362/148974673-ad914541-ee36-40a2-bcdc-e36ecd015619.png" width="200" />
<img src="https://user-images.githubusercontent.com/10376362/148975899-96d8947c-5a5a-4f2a-89c3-17a8ac6c7788.png" width="200" />
<img src="https://user-images.githubusercontent.com/10376362/148975902-37bd22e6-648f-49eb-9d7b-ae6967f0ed2f.png" width="200" />
<img src="https://user-images.githubusercontent.com/10376362/148975906-ba87035a-ef9d-4c7d-86f3-d98dabba363d.png" width="200" />
</p>

vs

Sample images from training that look fine:

![036000](https://user-images.githubusercontent.com/10376362/148974807-a6bab0f2-65eb-4971-988e-455067dad5e9.png)

![027000](https://user-images.githubusercontent.com/10376362/148974892-edd4edc0-9722-43fb-bc52-90cb2ca15b63.png)

**Comment by rosinality** [comment]
You will need to set --size to training sizes for the generate.py.

**Comment by harryli0088** [comment]
Awesome, thank you very much! I should have tried that out. My model was trained to generate images of size 256, not the default 1024.

By the way, I used your code to train these models for a class project! We even used the closed form factorization code. Thank you very much for publishing this!!

https://harryli0088.github.io/CS137-DNN-Project-StyleGAN2-Diamond/
