### ISSUE TITLE
CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by mostel** [rosinality/stylegan2-pytorch#30]
Hi, 

When I try to run the code on multiple GPUs (or even a single GPU), I get the following error:

```
  File "./stylegan2-pytorch/model.py", line 256, in forward
    out = F.conv_transpose2d(input, weight, padding=0, stride=2, groups=batch)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```

Any idea why this might be happening and how to resolve it?

My conda env uses python 3.7, cudatoolkit 10.1, cuda drivers 10.1 and pytorch 1.3. Thanks a lot!

**Comment by rosinality** [comment]
I found that conv_transpose2d is not supported if weight or input tensor is larger than certain sizes. You can use small batch sizes to avoid this.

**Comment by mostel** [comment]
Thanks for your response! I've read online that might be the case too, but in my case even with passing the argument --batch 1 I get the above error. In particular, I run this command

`CUDA_VISIBLE_DEVICES=0 python train.py --batch 1 ./data/ --size 1024  
`
 and still get the error. Any other idea why this might be happening? Thanks!

**Comment by mostel** [comment]
It seems to be working fine with size 512. However, it's strange that it doesn't work with size 1024, even with batch 1, as I'm training on an NVIDIA V100.

**Comment by rosinality** [comment]
Ah, I think the reason is number sample generated during training is too large for high resolutions. I added n_sample arguments in 16b85f60381ceaf3b4659879715f1e5e7aa18500, so you can reduce number of samples.

**Comment by mostel** [comment]
Great! That was it. Thanks v much again!

**Comment by mostel** [comment]
Great! That was it. Thanks v much again!
