### ISSUE TITLE
[Question] What is 'g_ema' and how does it differ from the generator 'g'?

### ISSUE THREAD

**Issue by cyrilzakka** [rosinality/stylegan2-pytorch#34]
Hello! More like a question rather than an issue. What is `g_ema`?
I can't seem to find its equivalent in the official `tensorflow` implementation. What is the difference between `g` the generator and `g_ema`?

https://github.com/rosinality/stylegan2-pytorch/blob/b0c6bf7dc42eee817c1e3dbf1d3a661b463ad607/train.py#L342-L344

**Comment by rosinality** [comment]
g_ema is running average of the weights of generator. You can find it in this: https://github.com/NVlabs/stylegan2/blob/4874628c7dfffaae01f89558c476842b475f54d5/training/training_loop.py#L240

**Comment by cyrilzakka** [comment]
Interesting, thank you for the reply!
