### ISSUE TITLE
RuntimeError: Error building extension 'fused'

### ISSUE THREAD

**Issue by sandhyalaxmiK** [rosinality/stylegan2-pytorch#35]
Hi,
Thanks for your great work
Currently i am trying for tweaking latents using InterFaceGan which requires pytorch pickle file. 
I want to implement this for stylegan2 architechture for which yours stylegan2-pytorch useful for creating pth file.
created a folder src in the stylegan2-pytorch directory and copied all the files in src directory.

Also written a shell script for converting weight is
convert_weight.sh (inside the src directory)
python convert_weight.py --repo ./stylegan2 stylegan2-ffhq-config-f.pkl

Now at outsider I have created a docker file like below
########################################################################
FROM tensorflow/tensorflow:1.15.0-gpu-py3
########Installing conda
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8
ENV PATH /opt/conda/bin:$PATH
RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates \
    libglib2.0-0 libxext6 libsm6 libxrender1 \
    git mercurial subversion
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    rm ~/miniconda.sh && \
    ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
    echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && \
    echo "conda activate base" >> ~/.bashrc
##INSTALL PYTORCH AND TORCHVISION
RUN conda install pytorch==1.3.1 torchvision==0.4.2 cudatoolkit=10.1 -c pytorch
###Install pillow with version 6.2.1
RUN conda install Pillow==6.2.1
ADD src/ /
RUN chmod +x ./convert_weight.sh
CMD ./convert_weight.sh
#########################################################################

installations i did are:
/Miniconda3
python3.7
pytorch==1.3.1
torchvision==0.4.2
cudatoolkit=10.1
Pillow==6.2.1

While running the docker file, in model.py while importing Generator getting error while running 
os.path.join(module_path, 'fused_bias_act_kernel.cu')
as
RuntimeError: Error building extension 'fused': [1/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /opt/conda/lib/python3.7/site-packages/torch/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++11 -c /op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
FAILED: fused_bias_act_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /opt/conda/lib/python3.7/site-packages/torch/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++11 -c /op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
In file included from /op/fused_bias_act_kernel.cu:11:0:
/opt/conda/lib/python3.7/site-packages/torch/include/ATen/cuda/CUDAContext.h:12:10: fatal error: cusparse.h: No such file or directory
 #include <cusparse.h>
          ^~~~~~~~~~~~
compilation terminated.
[2/3] c++ -MMD -MF fused_bias_act.o.d -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /opt/conda/lib/python3.7/site-packages/torch/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /op/fused_bias_act.cpp -o fused_bias_act.o
ninja: build stopped: subcommand failed.

I have installed whatever mentioned in the requirement place. 
Can any one help of how to solve

If you provide a Dockerfile for executing , installations helpful to me alot.
Thanks in advance.

Regards,
SandhyaLaxmi Kanna

**Comment by rosinality** [comment]
I think it is CUDA toolkit related error. Please check your CUDA installatons and paths.

**Comment by sandhyalaxmiK** [comment]
stylegan2 nvlabs requires cuda-10.0 , where as this pytorch version requires 10.1/10.2 .
I am in bit confusion whether to install cuda-10.0 or cuda-10.1???
Kindly give the solution

Thanks & Regards,
SandhyaLaxmi

**Comment by sandhyalaxmiK** [comment]
solved the issue

thanks

**Comment by grapeot** [comment]
@sandhyalaxmiK I've got the same problem. Can you kindly explain how you solved it? Thanks a lot!

**Comment by songyoyo** [comment]
@sandhyalaxmiK  I've got the same problem, too. Can you kindly explain how you solved it? Thanks a lot!

**Comment by mayankgrwl97** [comment]
I encountered a similar error even with cuda-10.1 installation (**_fatal error: cublas_v2.h: No such file or directory_**) <br>
#### Resolution

1. Re-install cuda-10.1 according to [this](https://medium.com/@exesse/cuda-10-1-installation-on-ubuntu-18-04-lts-d04f89287130) blog post.
2. Link missing header files according to [this](https://discuss.pytorch.org/t/no-such-file-or-directory-include-cublas-v2-h/73204/8) pytorch discussions article.
```
sudo ln -s /usr/local/cuda-10.2/targets/x86_64-linux/include/cublas_v2.h /usr/local/cuda/targets/x86_64-linux/include/cublas_v2.h
sudo ln -s /usr/local/cuda-10.2/targets/x86_64-linux/include/cublas_api.h /usr/local/cuda/targets/x86_64-linux/include/cublas_api.h
```

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1423, in _run_ninja_build
    check=True)
  File "/home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "infer.py", line 13, in <module>
    from stylegan2 import Generator
  File "/home/ubuntu/projects/python/xxxx/stylegan2/__init__.py", line 1, in <module>
    from .model import Generator
  File "/home/ubuntu/projects/python/xxxx/stylegan2/model.py", line 11, in <module>
    from .op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/ubuntu/projects/python/xxxx/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/ubuntu/projects/python/xxxx/stylegan2/op/fused_act.py", line 15, in <module>
    os.path.join(module_path, "fused_bias_act_kernel.cu"),
  File "/home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 921, in load
    is_python_module)
  File "/home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1109, in _jit_compile
    with_cuda=with_cuda)
  File "/home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1209, in _write_ninja_file_and_build_library
    error_prefix="Error building extension '{}'".format(name))
  File "/home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1436, in _run_ninja_build
    raise RuntimeError(message)
RuntimeError: Error building extension 'fused': [1/2] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/ubuntu/anaconda3/envs/stylegan_torch/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/projects/python/xxxx/stylegan2/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
FAILED: fused_bias_act_kernel.cuda.o 
/usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/site-packages/torch/include -isystem /home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/site-packages/torch/include/TH -isystem /home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /home/ubuntu/anaconda3/envs/stylegan_torch/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_70,code=sm_70 --compiler-options '-fPIC' -std=c++14 -c /home/ubuntu/projects/python/xxxx/stylegan2/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o 
In file included from /home/ubuntu/projects/python/xxxx/stylegan2/op/fused_bias_act_kernel.cu:11:0:
/home/ubuntu/anaconda3/envs/stylegan_torch/lib/python3.6/site-packages/torch/include/ATen/cuda/CUDAContext.h:7:10: fatal error: cublas_v2.h: No such file or directory
 #include <cublas_v2.h>
          ^~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

**Comment by TianpuSan** [comment]
> Hi, Thanks for your great work Currently i am trying for tweaking latents using InterFaceGan which requires pytorch pickle file. I want to implement this for stylegan2 architechture for which yours stylegan2-pytorch useful for creating pth file. created a folder src in the stylegan2-pytorch directory and copied all the files in src directory.
> 
> Also written a shell script for converting weight is convert_weight.sh (inside the src directory) python convert_weight.py --repo ./stylegan2 stylegan2-ffhq-config-f.pkl
> 
> Now at outsider I have created a docker file like below ######################################################################## FROM tensorflow/tensorflow:1.15.0-gpu-py3 ########Installing conda ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 ENV PATH /opt/conda/bin:$PATH RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 git mercurial subversion RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && /bin/bash ~/miniconda.sh -b -p /opt/conda && rm ~/miniconda.sh && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && echo "conda activate base" >> ~/.bashrc ##INSTALL PYTORCH AND TORCHVISION RUN conda install pytorch==1.3.1 torchvision==0.4.2 cudatoolkit=10.1 -c pytorch ###Install pillow with version 6.2.1 RUN conda install Pillow==6.2.1 ADD src/ / RUN chmod +x ./convert_weight.sh CMD ./convert_weight.sh #########################################################################
> 
> installations i did are: /Miniconda3 python3.7 pytorch==1.3.1 torchvision==0.4.2 cudatoolkit=10.1 Pillow==6.2.1
> 
> While running the docker file, in model.py while importing Generator getting error while running os.path.join(module_path, 'fused_bias_act_kernel.cu') as RuntimeError: Error building extension 'fused': [1/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /opt/conda/lib/python3.7/site-packages/torch/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++11 -c /op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o FAILED: fused_bias_act_kernel.cuda.o /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /opt/conda/lib/python3.7/site-packages/torch/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++11 -c /op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o In file included from /op/fused_bias_act_kernel.cu:11:0: /opt/conda/lib/python3.7/site-packages/torch/include/ATen/cuda/CUDAContext.h:12:10: fatal error: cusparse.h: No such file or directory #include <cusparse.h> ^~~~~~~~~~~~ compilation terminated. [2/3] c++ -MMD -MF fused_bias_act.o.d -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /opt/conda/lib/python3.7/site-packages/torch/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /op/fused_bias_act.cpp -o fused_bias_act.o ninja: build stopped: subcommand failed.
> 
> I have installed whatever mentioned in the requirement place. Can any one help of how to solve
> 
> If you provide a Dockerfile for executing , installations helpful to me alot. Thanks in advance.
> 
> Regards, SandhyaLaxmi Kanna



> Hi, Thanks for your great work Currently i am trying for tweaking latents using InterFaceGan which requires pytorch pickle file. I want to implement this for stylegan2 architechture for which yours stylegan2-pytorch useful for creating pth file. created a folder src in the stylegan2-pytorch directory and copied all the files in src directory.
> 
> Also written a shell script for converting weight is convert_weight.sh (inside the src directory) python convert_weight.py --repo ./stylegan2 stylegan2-ffhq-config-f.pkl
> 
> Now at outsider I have created a docker file like below ######################################################################## FROM tensorflow/tensorflow:1.15.0-gpu-py3 ########Installing conda ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 ENV PATH /opt/conda/bin:$PATH RUN apt-get update --fix-missing && apt-get install -y wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 git mercurial subversion RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && /bin/bash ~/miniconda.sh -b -p /opt/conda && rm ~/miniconda.sh && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh && echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc && echo "conda activate base" >> ~/.bashrc ##INSTALL PYTORCH AND TORCHVISION RUN conda install pytorch==1.3.1 torchvision==0.4.2 cudatoolkit=10.1 -c pytorch ###Install pillow with version 6.2.1 RUN conda install Pillow==6.2.1 ADD src/ / RUN chmod +x ./convert_weight.sh CMD ./convert_weight.sh #########################################################################
> 
> installations i did are: /Miniconda3 python3.7 pytorch==1.3.1 torchvision==0.4.2 cudatoolkit=10.1 Pillow==6.2.1
> 
> While running the docker file, in model.py while importing Generator getting error while running os.path.join(module_path, 'fused_bias_act_kernel.cu') as RuntimeError: Error building extension 'fused': [1/3] /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /opt/conda/lib/python3.7/site-packages/torch/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++11 -c /op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o FAILED: fused_bias_act_kernel.cuda.o /usr/local/cuda/bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /opt/conda/lib/python3.7/site-packages/torch/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++11 -c /op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o In file included from /op/fused_bias_act_kernel.cu:11:0: /opt/conda/lib/python3.7/site-packages/torch/include/ATen/cuda/CUDAContext.h:12:10: fatal error: cusparse.h: No such file or directory #include <cusparse.h> ^~~~~~~~~~~~ compilation terminated. [2/3] c++ -MMD -MF fused_bias_act.o.d -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /opt/conda/lib/python3.7/site-packages/torch/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /opt/conda/lib/python3.7/site-packages/torch/include/TH -isystem /opt/conda/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /opt/conda/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /op/fused_bias_act.cpp -o fused_bias_act.o ninja: build stopped: subcommand failed.
> 
> I have installed whatever mentioned in the requirement place. Can any one help of how to solve
> 
> If you provide a Dockerfile for executing , installations helpful to me alot. Thanks in advance.
> 
> Regards, SandhyaLaxmi Kanna

**Comment by TianpuSan** [comment]
I encountered the same problem. Could you please let me know how to solve it? I am really looking forward to your answer. Thank you so much!
