### ISSUE TITLE
Continue training from converted official weights?

### ISSUE THREAD

**Issue by kevinstan** [rosinality/stylegan2-pytorch#45]
Is it possible to continue training using the converted weights? I noticed that the converted weights only contain the state_dict for `g_ema`. However, [`train.py` ](https://github.com/rosinality/stylegan2-pytorch/blob/master/train.py#L374)assumes that the checkpoint has state_dict for `g`, `d`, `g_ema`, `g_optim`, and `d_optim`. 

Can `convert_weight.py` be modified to fix this? Or would it be easier to just train from scratch?

**Comment by rosinality** [comment]
I forgot to add argument documentations. You can use --gen and --disc arguments to convert_weight.py to add state_dict for g and d. I think you can load it, though you need to remove loading steps of g_optim and d_optim.
