### ISSUE TITLE
Overall batch size and batch size per gpu

### ISSUE THREAD

**Issue by mrybak-Novetta** [rosinality/stylegan2-pytorch#49]
It looks like in NVIDIA's styleGAN2, they split the batch between gpus such that 4 samples are sent to each gpu (minibatch_gpu_base = 4).  Based on the default settings in the repo and this [comment](https://github.com/rosinality/stylegan2-pytorch/issues/2#issuecomment-583703060), it seems as though you do not require 4 samples per gpu.  Why is that?

**Comment by rosinality** [comment]
NVIDIA used 8 GPUs, so total batch sizes will be 32. I have used 4 GPUs, so I used 8 images per GPU.

**Comment by CrossLee1** [comment]
P40 has about 22G memory in each gpu, why do you use batch 8 per GPU, instead of batch 16 per GPU.
Batch 8 per GPU only use about 8G memory.

Thanks

**Comment by rosinality** [comment]
@CrossLee1 Because I have used 4 gpus, and I wanted to match total batch size 32.
