### ISSUE TITLE
PILLOW_VERSION doesn't exist anymore

### ISSUE THREAD

**Issue by dave7895** [rosinality/stylegan2-pytorch#53]
From pillow version 7.0.0 PILLOW_VERSION doesn't exist anymore but is replaced by _version_.
````
# VERSION was removed in Pillow 6.0.0.
# PILLOW_VERSION was removed in Pillow 7.0.0.
# Use __version__ instead.
````

**Comment by rosinality** [comment]
Hmm could I know PILLOW_VERSION is used?

**Comment by dave7895** [comment]
no. I am sorry. I mistakenly thought the import of Pillow came from your script.
