### ISSUE TITLE
error when running train.py

### ISSUE THREAD

**Issue by qingzi02010** [rosinality/stylegan2-pytorch#6]
line 135 in train.py:
fake, latent = generator.module([test_in], return_latents=True)

when run train.py, it seems that "generator.module
AttributeError: 'Generator' object has no attribute 'module'".
My pytorch is 1.3.1, do you have some idea about that? Thank you so much!

**Comment by onion-liu** [comment]
Maybe you run the code on a single GPU, you should remove `.module`, which appears when using DistributedDataParallel.

**Comment by qingzi02010** [comment]
Yes, you are right, I only debug the code on a single GPU. So I had better run a distributed GPUs to get a correct result?

**Comment by rosinality** [comment]
If you want to test, you can run on single GPU with 71463b9aab9896b769e2fde5daa3bb59b91a3b92.

**Comment by qingzi02010** [comment]
1)Hi, wether running on a single GPU or distributed GPUs, the printed values “d_loss_val:.4f}; g: {g_loss_val:.4f}; r1: {r1_val:.4f}; ' f'path: {path_loss_val:.4f}; mean path: {mean_path_length_avg:.4f}'”   are all nan. 
2)I debug with a single GPU, it appears that ,  I can get fake_img with a normal value generated by generator,  with setting "requires_grad(generator, False), requires_grad(discriminator, True)". But after running   `r1_loss = d_r1_loss(real_pred, real_img)`, r1_loss is nan. When debugging into func d_r1_loss,  ```grad_real, = autograd.grad( outputs=real_pred.sum(), inputs=real_img, create_graph=True   )``` generate the grad_real with a nan value. 
3)I debug with a single GPU, with setting `requires_grad(generator, True)       requires_grad(discriminator, False)`, after running `fake_img, latents = generator(noise2, return_latents=True)` , fake_img is inf, and latents is inf.

**Comment by qingzi02010** [comment]
1)Hi, wether running on a single GPU or distributed GPUs, the printed values “d_loss_val:.4f}; g: {g_loss_val:.4f}; r1: {r1_val:.4f}; ' f'path: {path_loss_val:.4f}; mean path: {mean_path_length_avg:.4f}'” are all nan.
2)I debug with a single GPU, it appears that , `requires_grad(generator, False)    fake_img, _ = generator(noise1)` generate fake_img, of which fake_img[0:4] is 0,0,-inf,-inf.
3)`requires_grad(generator, True)    fake_img, _ = generator(noise1)` generate fake_img, of which fake_img[0:4] is -inf,-inf,-inf,-inf.
Do you have some idea about that? Thank you very much for your help!

**Comment by qingzi02010** [comment]
1)Hi, wether running on a single GPU or distributed GPUs, the printed values “d_loss_val:.4f}; g: {g_loss_val:.4f}; r1: {r1_val:.4f}; ' f'path: {path_loss_val:.4f}; mean path: {mean_path_length_avg:.4f}'” are all nan.
2)I debug with a single GPU, it appears that , requires_grad(generator, False) fake_img, _ = generator(noise1) generate fake_img, of which fake_img[0:4] is 0,0,-inf,-inf.
3)requires_grad(generator, True) fake_img, _ = generator(noise1) generate fake_img, of which fake_img[0:4] is -inf,-inf,-inf,-inf.

Do you have some idea about that? Thank you very much for your help!

**Comment by rosinality** [comment]
I suspect loss has been exploded after some iterations. Could I know your batch sizes? Maybe you can use lower learning rates and retry.

**Comment by qingzi02010** [comment]
On one single GPU, the batch size is 4. The problem occurs at the first time calling the generator forward function.

**Comment by rosinality** [comment]
Could you try this?

```python
import torch
from model import Generator

g = Generator(256, 512, 8).to('cuda')
x = torch.randn(4, 512).to('cuda')

print(g([x]))
```

If problem really occurs even at first forward, then maybe there are some numerical errors in generator implementations. But currently I don't know what it is.

**Comment by qingzi02010** [comment]
```
path = g_path_regularize(fake, latent, 0)
path[0].backward()
```
if I comment out these two lines, the value generated by generator is normal

**Comment by rosinality** [comment]
Hmm I don't know why as it will not update generator itself.

**Comment by qingzi02010** [comment]
`path = g_path_regularize(fake, latent, 0)     path[0].backward()`， function 'g_path_regularize' include operation `grad, = autograd.grad( outputs=(fake_img * noise).sum(), inputs=latents, create_graph=True )`, so backward will update generator, right?

**Comment by rosinality** [comment]
It will calculate gradients, but optimizer.step() is omitted so it will not update the parameters of the generator. As generator.zero_grad() will be called later so grad buffers will be cleaned.

**Comment by qingzi02010** [comment]
`    if args.distributed:
        fake, latent = generator.module([test_in], return_latents=True)     #for distributed gpu
    else:
        fake, latent = generator([test_in], return_latents=True)
    # for name,param in generator.named_parameters():
    #     if param.ndim==1:
    #         aa=str(param[0].cpu().detach().numpy())
    #     elif param.ndim==2:
    #         aa=str(param[0][0].cpu().detach().numpy())
    #     else:
    #         aa='param.ndim>2'
    #     print(name,aa)
    #     with open('generator_name_param_0.txt','a') as f:
    #         f.write(name+'####'+aa+'\n')
    path = g_path_regularize(fake, latent, 0)
    path[0].backward()
    # for name,param in generator.named_parameters():
    #     if param.ndim==1:
    #         aa=str(param[0].cpu().detach().numpy())
    #     elif param.ndim==2:
    #         aa=str(param[0][0].cpu().detach().numpy())
    #     else:
    #         aa='param.ndim>2'
    #     with open('generator_name_param_1.txt','a') as f:
    #         f.write(name+'####'+aa+'\n')
    fake_test, __ = generator([test_in], return_latents=True)`
Yes, I have checked that the parameter of generator is not updated. But, I check like that, fake is a normal value, but fake_test is inf. It is so strange. Can you reproduce that on one single gpu?

**Comment by rosinality** [comment]
I tested it, but in my cases it works without problem.

**Comment by qingzi02010** [comment]
‘’‘
if __name__ == '__main__':
    device = 'cuda'
    parser = argparse.ArgumentParser()
    parser.add_argument('--size', type=int, default=256)
    parser.add_argument('--channel_multiplier', type=int, default=2)
    args = parser.parse_args()
    args.latent = 512
    args.n_mlp = 8
    generator = Generator(
        args.size, args.latent, args.n_mlp, channel_multiplier=args.channel_multiplier
    ).to(device)
    
    test_in = torch.randn(1, args.latent, device=device)
    fake, latent = generator([test_in], return_latents=True)

    path = g_path_regularize(fake, latent, 0)
    path.backward()

    fake_test, __ = generator([test_in], return_latents=True)

’‘’
This is the main function in train.py, and it is so simple. The same error occured, 'fake' is normal, fake_test is inf, if 'path.backward()' is commented out, fake_test is normal. 
I am so confused that question, it is very strange, and do not know how to solve.

**Comment by rosinality** [comment]
Again, in my cases it works without a problem. Maybe there are some problems in custom kernels...Anyway, could you print output tensors during forward calculations? For example, add print(out) in the forward function of the generator.

**Comment by qingzi02010** [comment]
Hi, I debugged into generator, it appears that, once calling for functions of module 'op', such as function `upfirdn2d` or `fused_leaky_relu`,  unnormal value will be generated. Do you have some suggestion of that?

**Comment by qingzi02010** [comment]
Sorry, maybe it is the cuda and cudnn setting in my envs that caused the unnormal problem. I reset the configuration of the cuda and cudnn, the training process is normal. Thank you so much for your  support!

**Comment by CrossLee1** [comment]
@qingzi02010

**Comment by qingzi02010** [comment]
@CrossLee1 My cuda version is 10.0.130, cudnn version is 7.5.0
