### ISSUE TITLE
Get gray output when run the generate.py

### ISSUE THREAD

**Issue by kmaeii** [rosinality/stylegan2-pytorch#60]
Hi,
I got some '.pt' file by run the train.py successfully. And the output image is good. 
But when i want to run the generate.py , i got some just gray image like this :
![image](https://user-images.githubusercontent.com/50037669/76933373-ea135d00-6927-11ea-9a40-e10a870b524b.png)

By the way, 
 I changed the code in generat.py beause my gpu1 is used.
original:
g_ema = Generator(
        args.size, args.latent, args.n_mlp, channel_multiplier=args.channel_multiplier
    ).to(device)
checkpoint = torch.load(args.ckpt)
g_ema.load_state_dict(checkpoint['g_ema'])

changed:
g_ema = Generator(
        args.size, args.latent, args.n_mlp, channel_multiplier=args.channel_multiplier
    ).to(device)
checkpoint = torch.load(args.ckpt, map_location={'cuda:1':'cuda:2'})
g_ema.load_state_dict(checkpoint['g_ema'])

**Comment by rosinality** [comment]
Maybe --size argument is the problem.

**Comment by kmaeii** [comment]
> Maybe --size argument is the problem.

i set --size=128 both train.py and generate.py.

**Comment by kmaeii** [comment]
> Maybe --size argument is the problem.

i set --size=128 both train.py and generate.py.

**Comment by rosinality** [comment]
Maybe you need to load checkpoints and inspect model outputs. Hard to know the reasons of the problem. Sorry.

**Comment by kmaeii** [comment]
> Maybe you need to load checkpoints and inspect model outputs. Hard to know the reasons of the problem. Sorry.

Thank you for your help ! I will inspect the model again

**Comment by kmaeii** [comment]
> Maybe you need to load checkpoints and inspect model outputs. Hard to know the reasons of the problem. Sorry.
I fixed the problem by modify the code about torch device.

error:
device = torch.device('cuda:2')

right:
device = 'cuda'
torch.cuda.set_device(2)

I am confused about this , because it have no problem when i used 'device = torch.device('cuda:2')' in other code.

**Comment by rosinality** [comment]
Maybe it is related to custom CUDA kernels.
