### ISSUE TITLE
Why does  out of memory occur in 1024x1024 image training on batchsize 1 from scratch?

### ISSUE THREAD

**Issue by maguro27** [rosinality/stylegan2-pytorch#62]
Hi.
Thank you for implementing StyleGAN2 in PyTorch. I am impressed by your great job.
When I ran the train.py in 1024x1024 images on batchsize 1 after pre-processing image dataset to lmdb,  I met the error of "out of memory".
The run script is as follow,
`python -m torch.distributed.launch --nproc_per_node=4 --master_port=15122 train.py --batch 8 --size 1024 ./ffhq-dataset/lmdb_1024`
My environment is as follow,

> 8 Tesla V100 in 2 nodes
> PyTorch 1.4.0
> torchvision 0.5.0

Why do I meet the error of "out of memory" even I have 16GB of VRAM GPU?
Thanks.

**Comment by rosinality** [comment]
batch size specified in `--batch [INT]` will be the batch size per GPUs. If you have 8 GPUs, then you can use 4 for total batch size 32. Also you may need to adjust `--n_sample` to reduce number of samples generated during training.

**Comment by maguro27** [comment]
@rosinality 
Thank you for teaching me!
Although I tried to run train.py on per GPU batchsize 2 (i.e. using 16 Tesla V100 in 4nodes), I met the OoM again.
Now I cannot try to run script on per GPU batchsize 1 because of the computation resource restriction.
Next time, if I'll meet the OoM on per GPU batchsize 1, I'll reopen this issue.
Thanks :)
