### ISSUE TITLE
NoiseInjection is not used during training?

### ISSUE THREAD

**Issue by karfly** [rosinality/stylegan2-pytorch#64]
Hi @rosinality!

I noticed that in line [291](https://github.com/rosinality/stylegan2-pytorch/blob/master/model.py#L291) of [model.py](https://github.com/rosinality/stylegan2-pytorch/blob/master/model.py) the noise is always multiplicated by 0 if it's not passed as an argument:
```python
class NoiseInjection(nn.Module):
    def __init__(self):
        super().__init__()

        self.weight = nn.Parameter(torch.zeros(1))  # (!) Equals zero

    def forward(self, image, noise=None):
        if noise is None:
            batch, _, height, width = image.shape
            noise = image.new_empty(batch, 1, height, width).normal_()

        return image + self.weight * noise  # (!) multiplied by zero
```

The argument `noise=None` during all the training process which seems to be a very **SERIOUS BUG**. Can anybody clarify that?

**Comment by rosinality** [comment]
self.weight is learnable parameter.

**Comment by karfly** [comment]
@rosinality, didn't notice that. Thank you!
