### ISSUE TITLE
Possible to remove Tensorflow  dependency?

### ISSUE THREAD

**Issue by mbbrodie** [rosinality/stylegan2-pytorch#66]
Thank you for your amazing code! It's been extremely helpful for some dissertation projects.

I've recommended your codebase to quite a few academic/industry researchers. Their biggest adoption hurdle seems to be getting PyTorch & Tensorflow to play nicely together with CUDA. 

Do you think it's possible to remove the Tensorflow dependency altogether? (i.e. a pure-Pytorch approach?) Or do you recommend against re-implementing fused_bias_act / upfirdn2d in Pytorch?

Please let me know what you think - thanks!

**Comment by rosinality** [comment]
Currently this implementation does not depend on tensorflow except for converting checkpoints from tensorflow. Do you mean CUDA custom kernels (fused_bias_act & upfirdn2d)? It is not depend on tensorflow, but yes, it seems like that this causes many problems.

Actually this repository contains pytorch native implementations for upfirdn2d (https://github.com/rosinality/stylegan2-pytorch/blob/master/op/upfirdn2d.py#L152), and implementing fused_bias_act in pytorch will be easy. But it will cause quite large slowdowns during training (almost 2x).

**Comment by mbbrodie** [comment]
Sorry for the Tensorflow mixup, looks like the CUDA kernels are the main issue. 

I didn't realize how much the fused operations reduce runtime. But in the short-term, we can try using your native upfirdn2d code and replace fused_bias_act.

Thanks for responding so quickly.
