### ISSUE TITLE
G_mapping network removed PixelNorm()， but it in your code

### ISSUE THREAD

**Issue by Johnson-yue** [rosinality/stylegan2-pytorch#69]
why？？ it is good for performance ？？

**Comment by rosinality** [comment]
It is not removed: https://github.com/NVlabs/stylegan2/blob/cec605e0834de5404d5c7e5cead7053bdd0e4dde/training/networks_stylegan2.py#L285

**Comment by Johnson-yue** [comment]
Oh， I think it is an optional operate not must ，This is my fault

Thank you
