### ISSUE TITLE
There's still difference on the generated images using TensorFlow and Pyorch

### ISSUE THREAD

**Issue by wonjongJ** [rosinality/stylegan2-pytorch#73]
![astylegan2-ffhq-config-f (2)](https://user-images.githubusercontent.com/30016554/81142344-6cc0ac00-8faa-11ea-8c2f-59c6ca0aa6cc.png)

I converted the original weight of TensorFlow implementation into PyTorch version as you provided. As you can see, there's still a difference between the generated images with TensorFlow and PyTorch.  Is there any way to remove the gap between them?

**Comment by rosinality** [comment]
It is due to stochasticity of conv_transpose2d. You can use torch.backends.cudnn.deterministic = True to further reduce the gap. But anyway absolute differences between the results would already small.

**Comment by wonjongJ** [comment]
![astylegan2-ffhq-config-f (2)](https://user-images.githubusercontent.com/30016554/81192544-57bd3a80-8ff5-11ea-8a1b-b8c00e622d94.jpg)


Hi, thanks for your reply. I've already solved this problem. When I used matanby's commit version f79322a, there was no difference b/w the generated images. I guess that you might change something wrong after his commit. Thanks a lot!
