### ISSUE TITLE
Definition of FusedLeakyRelu

### ISSUE THREAD

**Issue by eladrich** [rosinality/stylegan2-pytorch#77]
Hi,
I was wondering whether you can explain how the FusedLeakyRelu differs from a regular LeakyRelu. Could not find any reference to such an operation in the original paper.

Thanks :)

**Comment by rosinality** [comment]
`FusedLeakyReLU(x)` is equivalent to `scale * LeakyReLU(x + bias)`.

**Comment by eladrich** [comment]
Cool, thanks!

**Comment by CharlesNord** [comment]
I really cannot understand why the authors don't use the offical operators of pytorch, the self defined operation is quiet annoying when I use a different version of pytorch.
