### ISSUE TITLE
Is it possible to do just inference eg: generate, interpolate, project on the cpu?

### ISSUE THREAD

**Issue by sdhnshu** [rosinality/stylegan2-pytorch#89]

**Comment by sdhnshu** [comment]
Seems possible

**Comment by rosinality** [comment]
Added native implementation for FusedLeakyReLU at be05887. I think you can now run the model on CPU.

**Comment by sdhnshu** [comment]
Thanks, I'll try it out today!

**Comment by sdhnshu** [comment]
Thanks for adding the native implementation for fusedleakyrelu. There's just one more small tweak needed. On the top of both fused_act.py and upfirdn2d.py you are loading the .cu files into a variable which fails on my cpu machine. I've hacked around it for now. Maybe you can load it only when needed? Thanks for replying so fast! :)

**Comment by datbu178** [comment]
@sdhnshu Have you run it successfully yet? I am trying to run it on cpu but still not succeed.

**Comment by Emmanuel357** [comment]
> Added native implementation for FusedLeakyReLU at [be05887](https://github.com/rosinality/stylegan2-pytorch/commit/be0588782047c8f303ece1aae6876d34535e9f59). I think you can now run the model on CPU.

Is there any native implementation for upfirdn2d.py?

**Comment by rosinality** [comment]
@Emmanuel357 Current implementation uses native implementation when model input on the cpu. You can refer to this: https://github.com/rosinality/stylegan2-pytorch/blob/master/op/upfirdn2d.py#L145.
