### ISSUE TITLE
How to load the already compiled C++/cuda extension? 

### ISSUE THREAD

**Issue by MengXinChengXuYuan** [rosinality/stylegan2-pytorch#9]
First, thank you so much for sharing your gggggggggggggggggggggggggggreat work! (I hate tf so much :()

I modified the code a little and I'm tring to debug the code in pycharm with a single GPU by switching nn.parallel.DistributedDataParallel to torch.nn.DataParallel.
The code goes well if excuted in shell command line and the extension lib are correctly generated, but if I run it in pycharm, I got:

'''
Traceback (most recent call last):
  File "/home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1030, in _build_extension_module
    check=True)
  File "/home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxxxx/xxxxx/stylegan2-pytorch-master/train.py", line 26, in <module>
    from model import Generator, Discriminator
  File "/home/xxxxx/xxxxx/stylegan2-pytorch-master/model.py", line 11, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/home/xxxxx/xxxxx/stylegan2-pytorch-master/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/home/xxxxx/xxxxx/stylegan2-pytorch-master/op/fused_act.py", line 6, in <module>
    fused = load('fused', sources=['op/fused_bias_act.cpp', 'op/fused_bias_act_kernel.cu'])
  File "/home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 830, in _jit_compile
    with_cuda=with_cuda)
  File "/home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 883, in _write_ninja_file_and_build
    _build_extension_module(name, build_directory, verbose)
  File "/home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1043, in _build_extension_module
    raise RuntimeError(message)
RuntimeError: Error building extension 'fused': [1/3] /home/xxxxx/share/cuda-10.0 /bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include/TH -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include/THC -isystem /home/xxxxx/share/cuda-10.0 /include -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++11 -c /home/xxxxx/xxxxx/stylegan2-pytorch-master/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
FAILED: fused_bias_act_kernel.cuda.o 
/home/xxxxx/share/cuda-10.0 /bin/nvcc -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include/TH -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include/THC -isystem /home/xxxxx/share/cuda-10.0 /include -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -std=c++11 -c /home/xxxxx/xxxxx/stylegan2-pytorch-master/op/fused_bias_act_kernel.cu -o fused_bias_act_kernel.cuda.o
/bin/sh: 1: /home/xxxxx/share/cuda-10.0: Permission denied
[2/3] c++ -MMD -MF fused_bias_act.o.d -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include/TH -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include/THC -isystem /home/xxxxx/share/cuda-10.0 /include -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/xxxxx/xxxxx/stylegan2-pytorch-master/op/fused_bias_act.cpp -o fused_bias_act.o
FAILED: fused_bias_act.o 
c++ -MMD -MF fused_bias_act.o.d -DTORCH_EXTENSION_NAME=fused -DTORCH_API_INCLUDE_EXTENSION_H -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include/TH -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/lib/python3.6/site-packages/torch/include/THC -isystem /home/xxxxx/share/cuda-10.0 /include -isystem /home/xxxxx/miniconda3/envs/py3.6_tensoflow1.14_n/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++11 -c /home/xxxxx/xxxxx/stylegan2-pytorch-master/op/fused_bias_act.cpp -o fused_bias_act.o
c++: error: /include: No such file or directory
ninja: build stopped: subcommand failed.
'''

How can I just load the pre-compiled extension library?  Which can skip the permission problem and save a lot of time

**Comment by rosinality** [comment]
I suspect build configurations is incorrect in pycharm, as it trys to add non-existing /include directory. Maybe it is related to conda environments.

**Comment by swj0418** [comment]
I had the same problem.
Do you think it is coming from using the Conda environment?

**Comment by rosinality** [comment]
Yes, I think it could cause the problem. But maybe there are other differences between plain cli environments and pycharm.

**Comment by swj0418** [comment]
I appreciate your input.
What I could find out so far is that, 
1. I had to have a Ninja package installed
2. Getting unsupported gpu_architecture 'compute_75'

The second error seems fatal, I am looking up for the solution as I am not familiar with this sort of errors.

**Comment by nadavbh12** [comment]
I got the same error running in Conda without pycharm.

**Comment by rosinality** [comment]
If it is not working at all, then maybe it is related to version of pytorch or cuda. I have tested with pytorch 1.3.1 with cuda 10.1/10.2.

**Comment by swj0418** [comment]
Yes, I am suspecting that the problem is associated with cuda version. 
I will verify after testing it on a new environment with cuda 10.1.

**Comment by nadavbh12** [comment]
I previously used PyTorch 1.2.
Upgrading to PyTorch 1.3.1 fixed the issue for me.

**Comment by swj0418** [comment]
Problem fixed with a mixture of multiple solutions. Thanks!

**Comment by MengXinChengXuYuan** [comment]
I thought it's a authority problem but it turns out to be cuda incompatible problem
Seems python from command line and pychram are using different cuda installed
Thank you all for the help! Closed

**Comment by MengXinChengXuYuan** [comment]
All right, still is there anyway that I can load the pre-compiled extension lib?
Even thougt it doesn't give any error now, but it still takes time to compile, and this is extremely inefficiency when you are in debug process :(

**Comment by rosinality** [comment]
Maybe you can check this https://github.com/pytorch/pytorch/blob/master/torch/utils/cpp_extension.py#L852 and why version is different.

**Comment by MengXinChengXuYuan** [comment]
Thx! I will try to figure it out !

**Comment by krips89** [comment]
> Problem fixed with a mixture of multiple solutions. Thanks!

Can you share your solution for others? 
I have pytorch 1.5 with cuda 10.2. I still get this error.

**Comment by shaibagon** [comment]
> All right, still is there anyway that I can load the pre-compiled extension lib?
> Even thougt it doesn't give any error now, but it still takes time to compile, and this is extremely inefficiency when you are in debug process :(

Have you find a way to re-use loaded `fused`  and `upfirdn2d` JIT objects? I am trying to train with distributed parallel and it compiles the libs over and over again.

See [this](https://discuss.pytorch.org/t/cpp-extension-load-for-distributed-environment/130138?u=shaibagon) issue.
