### ISSUE TITLE
Regarding noise injection in the generator

### ISSUE THREAD

**Issue by yunfan0621** [rosinality/stylegan2-pytorch#92]
Hi rosinality,

Thank you for your great work! I am recently studying your project and find the following piece of code confusing:

https://github.com/rosinality/stylegan2-pytorch/blob/609911be93f8e7bb5ad3277dbcaf3fc66a7f472c/model.py#L488-L494

Shouldn't we use initialized noises when `randomize_noise` is `True` and use `None` otherwise? Or maybe I take it wrong.

Thank you so much!

**Comment by rosinality** [comment]
If noise is None then random noises will be generated by this: https://github.com/rosinality/stylegan2-pytorch/blob/609911be93f8e7bb5ad3277dbcaf3fc66a7f472c/model.py#L287 If randomize_noise is False then noise parameters registered in the model will be used. (This is for converting checkpoints from the official code.)

**Comment by yunfan0621** [comment]
Got it. Thank you for your immediate response!

Closing this issue
