### ISSUE TITLE
Non leaking augmentations

### ISSUE THREAD

**Issue by affromero** [rosinality/stylegan2-pytorch#93]
Hello, is there any update for #84?
Thanks :)

**Comment by rosinality** [comment]
I have implemented non leaking augmentations and tested it with metfaces, but currently not fully verified effectiveness.

**Comment by affromero** [comment]
Is the 255 in [this](https://github.com/rosinality/stylegan2-pytorch/blob/master/train.py#L200) line of code related to this highlighted line in the screenshot?
<img width="683" alt="image" src="https://user-images.githubusercontent.com/9055917/88071179-cbda9980-cb73-11ea-8ee5-ec11d7f4c459.png">

**Comment by rosinality** [comment]
Yes.
