### ISSUE TITLE
Mode collapse without path length regularization

### ISSUE THREAD

**Issue by cientgu** [rosinality/stylegan2-pytorch#97]
I found when I don't use path length regularization (by set both d_reg_every and g_reg_every to a very big number like 1e10), the results will mode collapse, I am not sure if it's normal (according to the paper, it's not correct). I thought path length regularization should only be an auxiliary term to improve the performance.
![360000](https://user-images.githubusercontent.com/22503289/89433179-96899a80-d774-11ea-9082-4faa2b1ae455.png)

**Comment by rosinality** [comment]
Actually `--d_reg_every` controls the interval of R1 regularization.

**Comment by cientgu** [comment]
> Actually `--d_reg_every` controls the interval of R1 regularization.

Oh, so I should only set --g_reg_every to a big number and keep --d_reg_every to train without path length regularization? Thank you so much!

**Comment by rosinality** [comment]
Yes, it would work.
