### ISSUE TITLE
Closed Form Factorization on custom model

### ISSUE THREAD

**Issue by dvschultz** [rosinality/stylegan2-pytorch#99]
Hi,

When I perform the apply_factor.py script on a custom model I get grayed out images. 
![factor_index-19_degree-5 0](https://user-images.githubusercontent.com/161773/89962503-df2cd200-dc12-11ea-9ac0-6f7a2218900e.png)

When I use your converted FFHQ model everything looks fine, however. 

I noticed that my .pt file is ~150MB whereas yours is ~790MB. I just converted my file today with the most up-to-date repo.

Any ideas?

**Comment by rosinality** [comment]
Second row of images should be original samples (not manipulated) so I think it suggests there are problems in the model. Could you check generated samples from the model?

**Comment by dvschultz** [comment]
no issues in image generation

![000000 (2)](https://user-images.githubusercontent.com/161773/89966568-726b0500-dc1d-11ea-8448-daa4d780dfb2.png)
![000001](https://user-images.githubusercontent.com/161773/89966569-73039b80-dc1d-11ea-8f7b-94ab076c14ed.png)

**Comment by dvschultz** [comment]
ah, this was entirely my fault. the default size on the apply_factor.py is 256. once set to 1024 it works as expected.
